"""Add workspace_id in Task model

Revision ID: b28a24a19a2a
Revises: 2f4b8f9b61c2
Create Date: 2026-03-12 17:03:55.781383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28a24a19a2a'
down_revision: Union[str, Sequence[str], None] = '2f4b8f9b61c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_tasks_workspace_id'), 'tasks', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_workspace_id'), table_name='tasks')
    op.drop_column('tasks', 'workspace_id')
    # ### end Alembic commands ###
